### ISSUE TITLE
import 구문 절대경로 설정

### ISSUE THREAD

**Issue by rebi13** [BaekMinHyeok/calmsea#4]
`import * from '../../../../..`.........
을 방지하기 위해 src 또는 어느 폴더를 root로 설정하고, 해당 경로를 기준으로 import 구문을 반영하는 craco 라이브러리를 권장합니다. 

참고 링크 드립니다.
https://github.com/are-you-T/client
https://www.npmjs.com/package/@craco/craco

해당 사항은 우선순위가 매우 높거나, 매우 낮습니다.

매우 높음 : 언젠가는 절대경로를 지정하고자 할 경우 -> 바로 적용시키는 것이 정신건강에 이롭습니다.
매우 낮음 : 절대경로를 굳이 지정하고 싶지 않을 경우 -> 적용시키지 않고, 이슈를 닫아주세요.

**Comment by BaekMinHyeok** [comment]
craco 라이브러리 적용 완료
